"""Rule inventory for enterprise internal-doc lane (generalization audit)."""

from __future__ import annotations

from typing import Any, Literal

RuleClass = Literal[
    "reusable_generic_rule",
    "pattern_specific_rule",
    "pilot_only_rule",
    "coverage_or_abstain_rule",
    "synthesis_blocker_rule",
]

RULE_DEFINITIONS: list[dict[str, Any]] = [
    {
        "rule_id": "ED-PARSE-001",
        "component": "parsers",
        "class": "reusable_generic_rule",
        "description": "Detect source type by extension; read text from md/html/json/csv/xml/pdf",
        "input_pattern": "mixed-format file path",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-PARSE-002",
        "component": "parsers",
        "class": "reusable_generic_rule",
        "description": "Markdown section split by heading",
        "input_pattern": "markdown body",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-INGEST-001",
        "component": "ingest",
        "class": "reusable_generic_rule",
        "description": "Chunk evidence units (900/150 overlap) per section",
        "input_pattern": "parsed document text",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-ROUTE-001",
        "component": "doc_router",
        "class": "pattern_specific_rule",
        "description": "Heuristic route question metadata to logical doc ids via domain/topic tokens",
        "input_pattern": "question domain/category/item",
        "reuse_level": "medium",
        "demo_company_dependent": True,
        "productize": "needs_company_doc_registry",
        "notes": "DEMO_DOCUMENTS is RTX 7-step; abstract to per-company registry",
    },
    {
        "rule_id": "ED-MAP-001",
        "component": "doc_mapping",
        "class": "pilot_only_rule",
        "description": "CORPUS_DOC_PATTERNS map logical id to demo_company path hints",
        "input_pattern": "logical doc id + corpus document_id list",
        "reuse_level": "low",
        "demo_company_dependent": True,
        "productize": False,
    },
    {
        "rule_id": "ED-RETR-001",
        "component": "cross_doc_retriever",
        "class": "reusable_generic_rule",
        "description": "BM25 + lexical score_units over corpus index",
        "input_pattern": "natural language query",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-RETR-002",
        "component": "cross_doc_retriever",
        "class": "reusable_generic_rule",
        "description": "Planned-doc boost for single-doc retrieval",
        "input_pattern": "evidence plan primary_document_ids",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-RETR-003",
        "component": "cross_doc_retriever",
        "class": "pattern_specific_rule",
        "description": "Role-aware sub-queries per logical document role",
        "input_pattern": "cross-doc plan with roles dict",
        "reuse_level": "medium",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-RETR-004",
        "component": "cross_doc_retriever",
        "class": "pilot_only_rule",
        "description": "CSV role boost 2.0x for doc_evidence_csv",
        "input_pattern": "logical_id == doc_evidence_csv",
        "reuse_level": "low",
        "demo_company_dependent": True,
        "productize": False,
    },
    {
        "rule_id": "ED-RETR-005",
        "component": "cross_doc_retriever",
        "class": "pattern_specific_rule",
        "description": "Table-unit-first injection for financial metric questions",
        "input_pattern": "financial markers in question blob",
        "reuse_level": "medium",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-EXT-001",
        "component": "structured_extractor",
        "class": "reusable_generic_rule",
        "description": "Markdown pipe-table row parse + numeric cell extraction",
        "input_pattern": "evidence unit with | table rows",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-EXT-002",
        "component": "structured_extractor",
        "class": "reusable_generic_rule",
        "description": "score_row_match: item/subcategory/alias/token overlap + GENERIC_TOKENS penalty",
        "input_pattern": "table row label vs question metadata",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-EXT-003",
        "component": "structured_extractor",
        "class": "pilot_only_rule",
        "description": "ROW_ALIASES demo_company RTX table aliases",
        "input_pattern": "KR item keys (총 구성원, scope 1, etc.)",
        "reuse_level": "low",
        "demo_company_dependent": True,
        "productize": False,
    },
    {
        "rule_id": "ED-EXT-004",
        "component": "structured_extractor",
        "class": "pilot_only_rule",
        "description": "SEMANTIC_BRIDGE EN↔KR exact financial row labels",
        "input_pattern": "KR financial items → EN governance table rows",
        "reuse_level": "low",
        "demo_company_dependent": True,
        "productize": "needs_metric_family_registry",
    },
    {
        "rule_id": "ED-EXT-005",
        "component": "structured_extractor",
        "class": "pilot_only_rule",
        "description": "NARRATIVE_METRIC_PATTERNS (환경투자액 USD million, not_disclosed)",
        "input_pattern": "narrative bullets in business doc",
        "reuse_level": "low",
        "demo_company_dependent": True,
        "productize": "needs_pattern_family_registry",
    },
    {
        "rule_id": "ED-EXT-006",
        "component": "structured_extractor",
        "class": "coverage_or_abstain_rule",
        "description": "source_not_disclosed_for_metric when Not disclosed row matches",
        "input_pattern": "not disclosed / 미공시 in matched row",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-EXT-007",
        "component": "structured_extractor",
        "class": "reusable_generic_rule",
        "description": "wrong_row_risk flag when weak token overlap with extra row tokens",
        "input_pattern": "row_match_score < 0.85 without alias/bridge",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-AGG-001",
        "component": "evidence_aggregator",
        "class": "reusable_generic_rule",
        "description": "Primary-doc numeric override Not disclosed supporting values",
        "input_pattern": "multi-doc candidates with disclosure conflict",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-AGG-002",
        "component": "evidence_aggregator",
        "class": "reusable_generic_rule",
        "description": "Numeric conflict detection with 5% tolerance",
        "input_pattern": "conflicting numeric candidates same metric",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-AGG-003",
        "component": "evidence_aggregator",
        "class": "pilot_only_rule",
        "description": "GOVERNANCE_ANCHOR_METRICS + doc_06_governance single-source sufficiency",
        "input_pattern": "financial metrics in EN governance table",
        "reuse_level": "low",
        "demo_company_dependent": True,
        "productize": "needs_authoritative_source_registry",
    },
    {
        "rule_id": "ED-AGG-004",
        "component": "evidence_aggregator",
        "class": "reusable_generic_rule",
        "description": "metric_absent_in_role via corpus probe (min_score 0.1)",
        "input_pattern": "optional role without parseable metric",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-AGG-005",
        "component": "evidence_aggregator",
        "class": "reusable_generic_rule",
        "description": "single_source_sufficient when one authoritative role has metric, others absent",
        "input_pattern": "resolved value + roles_absent_by_design",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-AGG-006",
        "component": "evidence_aggregator",
        "class": "pilot_only_rule",
        "description": "NARRATIVE_PROBE_METRICS probe doc_01_business for 환경투자액",
        "input_pattern": "item == 환경투자액 cross-doc GHG cluster",
        "reuse_level": "low",
        "demo_company_dependent": True,
        "productize": False,
    },
    {
        "rule_id": "ED-DIAG-001",
        "component": "diagnostics",
        "class": "reusable_generic_rule",
        "description": "Fail taxonomy: parser/retrieval/aggregation/synthesis/coverage_gap",
        "input_pattern": "plan + retrieval result",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-DIAG-002",
        "component": "diagnostics",
        "class": "coverage_or_abstain_rule",
        "description": "coverage_gap when planned logical doc not in corpus map",
        "input_pattern": "unmapped primary/supporting logical ids",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-DIAG-003",
        "component": "diagnostics",
        "class": "synthesis_blocker_rule",
        "description": "synthesis_gap for qualitative without full doc coverage",
        "input_pattern": "kind=qualitative + evidence_plan_coverage < 1",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
    {
        "rule_id": "ED-QUAL-001",
        "component": "structured_extractor",
        "class": "synthesis_blocker_rule",
        "description": "qualitative_not_supported_in_pilot — defer to synthesis phase",
        "input_pattern": "kind=qualitative",
        "reuse_level": "high",
        "demo_company_dependent": False,
        "productize": True,
    },
]


def export_rule_inventory(path: str | None = None) -> dict[str, Any]:
    """Build inventory payload with counts by class."""
    by_class: dict[str, int] = {}
    for rule in RULE_DEFINITIONS:
        cls = str(rule["class"])
        by_class[cls] = by_class.get(cls, 0) + 1

    payload: dict[str, Any] = {
        "lane": "enterprise_internal_doc",
        "baseline_artifact": "reports/demo_company_aggregation_sufficiency_20260618-150423",
        "rule_count": len(RULE_DEFINITIONS),
        "by_class": by_class,
        "rules": RULE_DEFINITIONS,
    }
    if path:
        from pathlib import Path
        import json

        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return payload
